# Generated by Django 5.2 on 2025-12-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('CPP', 'C++'), ('JAVA', 'Java')]),
        ),
    ]
