# Generated by Django 5.2 on 2025-12-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemReview',
        ),
    ]
