# Generated by Django 5.2 on 2025-10-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'position')},
        ),
    ]
