# Generated by Django 5.2 on 2025-11-08 20:45

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonimage',
            name='image',
            field=models.ImageField(upload_to=courses.models.get_lesson_image_path),
        ),
    ]
